config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  resources :users, only: [:index, :show, :update], shallow: true
  resources :records, only: :create

  get '/records/introduction/new', as: 'new_introduction'
  post '/records/introduction', to: 'records/introduction#create', as: 'create_introduction'

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :author, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def require_login
    authenticate_user!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login

  def index
    @records = Record.order(created_at: :desc)
  end
end

app/controllers/records/introduction_controller.rb
class Records::IntroductionController < ApplicationController
  def new; end

  def introduction_params
    @introduction_params ||= params.permit(
      %i[
        firstname
        patronymic
        surname
        birthdate
        address
      ]
    ).to_h
  end

  def introduction_hash
    @introduction_hash ||= {
      'тип'           => 'представление',
      'имя'           => introduction_params['firstname'],
      'отчество'      => introduction_params['patronymic'],
      'фамилия'       => introduction_params['surname'],
      'дата рождения' => introduction_params['birthdate'],
      'адрес'         => introduction_params['address'],
    }
  end

  def create
    Record.create!(
      {
        content: introduction_hash.to_yaml,
        author_id: current_user.id,
      }
    )

    redirect_to root_path
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :require_login

  def create
    @record = Record.create!(
      params
        .permit(:content).to_h
        .merge(author_id: current_user.id)
    )

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def index
    @users = User.where.not(public_key: nil).where.not(id: current_user.id).order(email: :asc)
  end

  def update
    @user = current_user
    @user.public_key = params.require(:user).require(:public_key)
    @user.fingerprint = params.require(:user).require(:fingerprint)
    @user.save
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_header.html.slim
header
  nav
    a href=root_path Book
    a href=users_path Profile

app/views/home/index.html.slim
nav
  a href=new_introduction_path Introduction

p
  strong Records

- @records.each do |record|
  div
    small = l record.created_at, format: :default
    br
    small = record.author.email
    pre = record.content
    hr

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/records/introduction/new.html.slim
h4 Introduction

p Let's fill in Introduction form!

div.center
  = form_with url: create_introduction_path do |f|
    = f.label :firstname
    br
    = f.text_field :firstname, required: true
    br

    = f.label :patronymic
    br
    = f.text_field :patronymic
    br

    = f.label :surname
    br
    = f.text_field :surname
    br

    = f.label :birthdate
    br
    = f.date_field :birthdate
    br

    = f.label :address
    br
    = f.text_field :address
    br

    = f.submit "Save"

app/views/users/index.html.slim
p Hello #{current_user.email}!

h4 Key Management
- if current_user.public_key.present?
  h5 Your public key
  pre = current_user.public_key

div *{"data-controller" => "keys"}
  label for="full_name" Full name
  br
  input id="full_name" type="text" *{"data-target" => "keys.username"}
  br

  label for="passphrase" Passphrase
  br
  input id="passphrase" type="password" *{"data-target" => "keys.passphrase"}
  br

  = form_with model: current_user do |f|
    = f.hidden_field :email, name: nil, value: current_user.email, data: { target: "keys.email" }

    button data-action="click->keys#generate" Generate Key Pair
    br

    = f.label :public_key
    br
    = f.text_area :public_key, required: true, data: { target: "keys.publicKey" }
    br

    = f.label :private_key
    br
    = f.text_area :private_key, name: nil, data: { target: "keys.privateKey" }
    br

    = f.label :fingerprint
    br
    = f.text_area :fingerprint, required: true, data: { target: "keys.fingerprint" }
    br

    = f.submit "Update Keys", data: { action: "click->keys#register" }